name: Format
on:
  workflow_run:
    workflows: [ "Tests" ]
    types:
      - completed

permissions:
  contents: write

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"