name: Tests
on: [ push, pull_request ]

permissions:
  contents: write
  checks: write
  id-token: write

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'spring_project1' # Optional, default value is "test". The specified database which will be create
          mysql root password: testpassword # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: testpassword # Required if "mysql user" exists. The password for the "mysql user"

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always() # always run even if the previous step fails
        with:
          name: JUnit tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true